In [0]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print('a.shape:',a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape: (3, 5)


In [0]:
print('a.ndim:',a.ndim)

a.ndim: 2


In [0]:
print('a,dtype.name:',a.dtype.name)

a,dtype.name: int64


In [0]:
print('a.itemsize:',a.itemsize)  #array가 갖고있는 데이터 사이즈

a.itemsize: 8


In [0]:
print('a.size:',a.size)

a.size: 15


In [0]:
print('type(a):',type(a))  #type하고 shape 헷갈리지말자.....type은 넘파이인지 텐서플로어인지 구분

type(a): <class 'numpy.ndarray'>


###**Numpy 어레이만들기**

In [0]:
#np.array()
import numpy as np
temp=[2,3,4]
a=np.array([2,3,4])
print(a)
print(temp)

[2 3 4]
[2, 3, 4]


In [0]:
print(type(a))
print(type(temp))

<class 'numpy.ndarray'>
<class 'list'>


In [0]:
print('a.ndim:',a.ndim) 
print('a.dtype',a.dtype)

a.ndim: 1
a.dtype int64


In [0]:
temp2=[1.2, 3.5, 5.1]
b=np.array(temp2)
print(b.dtype)

float64


In [0]:
import numpy as np

c=np.array([(1.5,2,3),(4,5,6)])
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [0]:
import numpy as np

d=np.array([[1,2],[3,4]], dtype=complex)
print(d)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


###**np.zeros(), np.ones(),np.empty()**

In [0]:
import numpy as np

a=np.zeros((3,4)) ##검은색 배열만들기
b=np.ones((2,3,4),dtype=np.int16)*255 ##흰색 배열만들기
c=np.empty((2,3))
print(a)
print(b)
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]
[[7.06416102e-304 7.06416102e-304 7.06416102e-304]
 [7.06416102e-304 7.06416102e-304 7.06416102e-304]]


###**np.arange()**

In [0]:
import numpy as np

a=np.arange(10,30,5)
b=np.arange(0,2,0.3)
print(a)
print(b)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [0]:
import numpy as np

a=np.arange(12).reshape(4,3) #2d array
b=np.arange(24).reshape(2,3,4) #3d array

print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
import numpy as np
import sys
a=np.arange(10000).reshape(100,100)
np.set_printoptions(threshold=sys.maxsize)
#print(sys.maxsize)
#print(a)


###**numpy araray의 산술연산***

In [0]:
a=np.array([20,30,40,50])
b=np.arange(4)

print(a)
print(b)

c=a-b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [0]:
import numpy as np
a=np.array([20,30,40,50])
b=np.arange(4)
print(b**2)
for i in range(0, 90, 1):
  print(np.sin(i))

[0 1 4 9]
0.0
0.8414709848078965
0.9092974268256817
0.1411200080598672
-0.7568024953079282
-0.9589242746631385
-0.27941549819892586
0.6569865987187891
0.9893582466233818
0.4121184852417566
-0.5440211108893698
-0.9999902065507035
-0.5365729180004349
0.4201670368266409
0.9906073556948704
0.6502878401571168
-0.2879033166650653
-0.9613974918795568
-0.750987246771676
0.14987720966295234
0.9129452507276277
0.8366556385360561
-0.008851309290403876
-0.8462204041751706
-0.9055783620066239
-0.13235175009777303
0.7625584504796027
0.956375928404503
0.27090578830786904
-0.6636338842129675
-0.9880316240928618
-0.404037645323065
0.5514266812416906
0.9999118601072672
0.5290826861200238
-0.428182669496151
-0.9917788534431158
-0.6435381333569995
0.2963685787093853
0.9637953862840878
0.7451131604793488
-0.158622668804709
-0.9165215479156338
-0.8317747426285983
0.017701925105413577
0.8509035245341184
0.9017883476488092
0.123573122745224
-0.7682546613236668
-0.9537526527594719
-0.26237485370392877
0.670229

###**numpy array 곱셈연산,행렬곱 연산**

In [0]:
import numpy as np

a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])

print(a*b)    # elementwise product
print(a@b)  # matrix product
print(a.dot(b)) # another matrix product


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [0]:
import numpy as np

a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
print(a)

[[3 3 3]
 [3 3 3]]


###**단항연산: sum(), min(), max()**

In [0]:
import numpy as np

temp=[1,2,3,4]
a=np.array(temp)
print(a.sum())
print(a.min())
print(a.max())

10
1
4


###**특정 축에 대해 연산 적용**

In [0]:
import numpy as np

b=np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0)) #열의 합
print(b.sum(axis=1)) #행의 합
print(b.sum())


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
66


###**Numpy 범용함수**

In [0]:
import numpy as np
B=np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

C=np.array([2.,-1.,4.])
print(np.add(B,C))



[0 1 2]
[1.         2.71828183 7.3890561 ]


### **Numpy index/slice/iterate**

In [0]:
#index

import numpy as np
a=np.arange(10)**2
print(a)
print(a[2])
print(a[-1])

[ 0  1  4  9 16 25 36 49 64 81]
4
81


In [0]:
#slicing 파이썬과 동일하게 어레이를 slicing할 수 있다.
import numpy as np

a=np.arange(10)**2
print(a[2:5])
print(a[:4:2])
print(a[::-1])


[ 4  9 16]
[0 4]
[81 64 49 36 25 16  9  4  1  0]


###**Iterating**

In [0]:
import numpy as np

a=np.arange(10)**2
print(a)
#iterating
for i in a:
  print(i*2)

[ 0  1  4  9 16 25 36 49 64 81]
0
2
8
18
32
50
72
98
128
162


In [0]:
import numpy as np

def f(x,y):
  return x+y

b=np.fromfunction(f,(5,4),dtype=int)

print(b)
print(b[2,3]) #index
print(b[:,1])
print(b[1:3,:])

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
5
[1 2 3 4 5]
[[1 2 3 4]
 [2 3 4 5]]


In [0]:
print(b[-1])

[4 5 6 7]


In [0]:
print(b[-1,:])

[4 5 6 7]


In [0]:
for i in b.flat:
  print(i)

0
1
2
3
1
2
3
4
2
3
4
5
3
4
5
6
4
5
6
7


In [0]:
import numpy as np

b=np.arange(48).reshape(2,2,3,4) #4d array
print(b)
for i in b.flat:
  print(i)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47


###**numpy array의 형태를 바꾸기**

In [0]:
import numpy as np
b= np.arange(12).reshape(3,4)
print(b)
print(b.shape)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [0]:
print(b.ravel()) #1차원으로 펼쳐진 어레이를 반환한다.

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [0]:
#reshape: 새로운 형태를 갖는 어레이를 반환한다.
print(b.reshape(6,2))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [0]:
#전치행렬 어레이를 반환한다.
print(b.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


###**올림(ceiling), 내림함수(floor) ** **굵은 텍스트**

In [0]:
import numpy as np

a=np.array([-1.7, -1.4, -0.2, 0.2, 1.4 ,1.7, 2])
print(np.floor(a))

[-2. -2. -1.  0.  1.  1.  2.]


In [0]:
import numpy as np

a=np.array([-1.7, -1.4, -0.2, 0.2, 1.4 ,1.7, 2])
print(np.ceil(a))

[-1. -1. -0.  1.  2.  2.  2.]


In [0]:
import numpy as np

a=np.array([-1.7, -1.4, -0.2, 0.2, 1.4 ,1.7, 2])
print(np.around(a))

[-2. -1. -0.  0.  1.  2.  2.]


In [0]:
import numpy as np

a=np.array([-1.7, -1.4, -0.2, 0.2, 1.4 ,1.7, 2])
print(np.amax(a))
print(np.amin(a))

2.0
-1.7


In [0]:
print(np.argmax(a))
print(np.argmin(a))

6
0
